name: npm diff

on:
  pull_request_target:
    types: [opened]

jobs:
  npm-diff:
    if: ${{ startsWith(github.head_ref, 'dependabot/npm_and_yarn/') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: ybiquitous/npm-diff-action@884b3cb138c2df7217007213936317947bf8fdc4 # v1.7.2
